module Components.Header exposing (view)

import Html
    exposing
        ( Html
        , a
        , div
        , i
        , img
        , input
        , li
        , p
        , small
        , span
        , text
        , ul
        )
import Html.Attributes
    exposing
        ( alt
        , attribute
        , class
        , href
        , id
        , placeholder
        , src
        , type_
        )
import Session exposing (User)


view : User -> Html msg
view user =
    div [ class "header navbar" ]
        [ div [ class "header-container" ]
            [ ul [ class "nav-left" ]
                [ li []
                    [ a [ id "sidebar-toggle", class "sidebar-toggle", href "javascript:void(0);" ]
                        [ i [ class "ti-menu" ]
                            []
                        ]
                    ]
                , li [ class "search-box" ]
                    [ a [ class "search-toggle no-pdd-right", href "javascript:void(0);" ]
                        [ i [ class "search-icon ti-search pdd-right-10" ]
                            []
                        , i [ class "search-icon-close ti-close pdd-right-10" ]
                            []
                        ]
                    ]
                , li [ class "search-input" ]
                    [ input [ class "form-control", type_ "text", placeholder "Search..." ]
                        []
                    ]
                ]
            , ul [ class "nav-right" ]
                [ li [ class "notifications dropdown" ]
                    [ span [ class "counter bgc-red" ]
                        [ text "3" ]
                    , a [ href "", class "dropdown-toggle no-after", attribute "data-toggle" "dropdown" ]
                        [ i [ class "ti-bell" ]
                            []
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li [ class "pX-20 pY-15 bdB" ]
                            [ i [ class "ti-bell pR-10" ]
                                []
                            , span [ class "fsz-sm fw-600 c-grey-900" ]
                                [ text "Notifications" ]
                            ]
                        , li []
                            [ ul [ class "ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm" ]
                                [ li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src user.photoUrl, alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ span []
                                                [ span [ class "fw-500" ]
                                                    [ text "Me" ]
                                                , span [ class "c-grey-600" ]
                                                    [ text "liked your"
                                                    , span [ class "text-dark" ]
                                                        [ text "post" ]
                                                    ]
                                                ]
                                            , p [ class "m-0" ]
                                                [ small [ class "fsz-xs" ]
                                                    [ text "5 mins ago" ]
                                                ]
                                            ]
                                        ]
                                    ]
                                , li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src "https://randomuser.me/api/portraits/men/2.jpg", alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ span []
                                                [ span [ class "fw-500" ]
                                                    [ text "Moo Doe" ]
                                                , span [ class "c-grey-600" ]
                                                    [ text "liked your"
                                                    , span [ class "text-dark" ]
                                                        [ text "cover image" ]
                                                    ]
                                                ]
                                            , p [ class "m-0" ]
                                                [ small [ class "fsz-xs" ]
                                                    [ text "7 mins ago" ]
                                                ]
                                            ]
                                        ]
                                    ]
                                , li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src "https://randomuser.me/api/portraits/men/3.jpg", alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ span []
                                                [ span [ class "fw-500" ]
                                                    [ text "Lee Doe" ]
                                                , span [ class "c-grey-600" ]
                                                    [ text "commented on your"
                                                    , span [ class "text-dark" ]
                                                        [ text "video" ]
                                                    ]
                                                ]
                                            , p [ class "m-0" ]
                                                [ small [ class "fsz-xs" ]
                                                    [ text "10 mins ago" ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , li [ class "pX-20 pY-15 ta-c bdT" ]
                            [ span []
                                [ a [ href "", class "c-grey-600 cH-blue fsz-sm td-n" ]
                                    [ text "View All Notifications"
                                    , i [ class "ti-angle-right fsz-xs mL-10" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                , li [ class "notifications dropdown" ]
                    [ span [ class "counter bgc-blue" ]
                        [ text "3" ]
                    , a [ href "", class "dropdown-toggle no-after", attribute "data-toggle" "dropdown" ]
                        [ i [ class "ti-email" ]
                            []
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li [ class "pX-20 pY-15 bdB" ]
                            [ i [ class "ti-email pR-10" ]
                                []
                            , span [ class "fsz-sm fw-600 c-grey-900" ]
                                [ text "Emails" ]
                            ]
                        , li []
                            [ ul [ class "ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm" ]
                                [ li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src "https://randomuser.me/api/portraits/men/1.jpg", alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ div []
                                                [ div [ class "peers jc-sb fxw-nw mB-5" ]
                                                    [ div [ class "peer" ]
                                                        [ p [ class "fw-500 mB-0" ]
                                                            [ text "John Doe" ]
                                                        ]
                                                    , div [ class "peer" ]
                                                        [ small [ class "fsz-xs" ]
                                                            [ text "5 mins ago" ]
                                                        ]
                                                    ]
                                                , span [ class "c-grey-600 fsz-sm" ]
                                                    [ text "Want to create your own customized data generator for your app..." ]
                                                ]
                                            ]
                                        ]
                                    ]
                                , li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src "https://randomuser.me/api/portraits/men/2.jpg", alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ div []
                                                [ div [ class "peers jc-sb fxw-nw mB-5" ]
                                                    [ div [ class "peer" ]
                                                        [ p [ class "fw-500 mB-0" ]
                                                            [ text "Moo Doe" ]
                                                        ]
                                                    , div [ class "peer" ]
                                                        [ small [ class "fsz-xs" ]
                                                            [ text "15 mins ago" ]
                                                        ]
                                                    ]
                                                , span [ class "c-grey-600 fsz-sm" ]
                                                    [ text "Want to create your own customized data generator for your app..." ]
                                                ]
                                            ]
                                        ]
                                    ]
                                , li []
                                    [ a [ href "", class "peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100" ]
                                        [ div [ class "peer mR-15" ]
                                            [ img [ class "w-3r bdrs-50p", src "https://randomuser.me/api/portraits/men/3.jpg", alt "" ]
                                                []
                                            ]
                                        , div [ class "peer peer-greed" ]
                                            [ div []
                                                [ div [ class "peers jc-sb fxw-nw mB-5" ]
                                                    [ div [ class "peer" ]
                                                        [ p [ class "fw-500 mB-0" ]
                                                            [ text "Lee Doe" ]
                                                        ]
                                                    , div [ class "peer" ]
                                                        [ small [ class "fsz-xs" ]
                                                            [ text "25 mins ago" ]
                                                        ]
                                                    ]
                                                , span [ class "c-grey-600 fsz-sm" ]
                                                    [ text "Want to create your own customized data generator for your app..." ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , li [ class "pX-20 pY-15 ta-c bdT" ]
                            [ span []
                                [ a [ href "email.html", class "c-grey-600 cH-blue fsz-sm td-n" ]
                                    [ text "View All Email"
                                    , i [ class "fs-xs ti-angle-right mL-10" ]
                                        []
                                    ]
                                ]
                            ]
                        ]
                    ]
                , li [ class "dropdown" ]
                    [ a [ href "", class "dropdown-toggle no-after peers fxw-nw ai-c lh-1", attribute "data-toggle" "dropdown" ]
                        [ div [ class "peer mR-10" ]
                            [ img [ class "w-2r bdrs-50p", src user.photoUrl, alt "" ]
                                []
                            ]
                        , div [ class "peer" ]
                            [ span [ class "fsz-sm c-grey-900" ]
                                [ text user.name ]
                            ]
                        ]
                    , ul [ class "dropdown-menu fsz-sm" ]
                        [ li []
                            [ a [ href "", class "d-b td-n pY-5 bgcH-grey-100 c-grey-700" ]
                                [ i [ class "ti-settings mR-10" ]
                                    []
                                , span []
                                    [ text "Setting" ]
                                ]
                            ]
                        , li []
                            [ a [ href "", class "d-b td-n pY-5 bgcH-grey-100 c-grey-700" ]
                                [ i [ class "ti-user mR-10" ]
                                    []
                                , span []
                                    [ text "Profile" ]
                                ]
                            ]
                        , li []
                            [ a [ href "email.html", class "d-b td-n pY-5 bgcH-grey-100 c-grey-700" ]
                                [ i [ class "ti-email mR-10" ]
                                    []
                                , span []
                                    [ text "Messages" ]
                                ]
                            ]
                        , li [ attribute "role" "separator", class "divider" ]
                            []
                        , li []
                            [ a [ href "", class "d-b td-n pY-5 bgcH-grey-100 c-grey-700" ]
                                [ i [ class "ti-power-off mR-10" ]
                                    []
                                , span []
                                    [ text "Logout" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
