module Components.Sidebar exposing (view)

import Html exposing (Html, a, div, h5, i, img, li, span, text, ul)
import Html.Attributes exposing (class, href, src, alt)


view : Html msg
view =
    div [ class "sidebar" ]
        [ div [ class "sidebar-inner" ]
            [ div [ class "sidebar-logo" ]
                [ div [ class "peers ai-c fxw-nw" ]
                    [ div [ class "peer peer-greed" ]
                        [ a [ class "sidebar-link td-n", href "index.html" ]
                            [ div [ class "peers ai-c fxw-nw" ]
                                [ div [ class "peer" ]
                                    [ div [ class "logo" ]
                                        [ img [ src "assets/static/images/logo.png", alt "" ]
                                            []
                                        ]
                                    ]
                                , div [ class "peer peer-greed" ]
                                    [ h5 [ class "lh-1 mB-0 logo-text" ]
                                        [ text "InteroCare" ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "peer" ]
                        [ div [ class "mobile-toggle sidebar-toggle" ]
                            [ a [ href "", class "td-n" ]
                                [ i [ class "ti-arrow-circle-left" ]
                                    []
                                ]
                            ]
                        ]
                    ]
                ]
            , ul [ class "sidebar-menu scrollable pos-r" ]
                [ li [ class "nav-item mT-30 actived" ]
                    [ a [ class "sidebar-link", href "index.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-blue-500 ti-home" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Dashboard" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "email.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-brown-500 ti-email" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Email" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "compose.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-blue-500 ti-share" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Compose" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "calendar.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-deep-orange-500 ti-calendar" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Calendar" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "chat.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-deep-purple-500 ti-comment-alt" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Chat" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "charts.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-indigo-500 ti-bar-chart" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Charts" ]
                        ]
                    ]
                , li [ class "nav-item" ]
                    [ a [ class "sidebar-link", href "forms.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-light-blue-500 ti-pencil" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Forms" ]
                        ]
                    ]
                , li [ class "nav-item dropdown" ]
                    [ a [ class "sidebar-link", href "ui.html" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-pink-500 ti-palette" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "UI Elements" ]
                        ]
                    ]
                , li [ class "nav-item dropdown" ]
                    [ a [ class "dropdown-toggle", href "javascript:void(0);" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-orange-500 ti-layout-list-thumb" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Tables" ]
                        , span [ class "arrow" ]
                            [ i [ class "ti-angle-right" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li []
                            [ a [ class "sidebar-link", href "basic-table.html" ]
                                [ text "Basic Table" ]
                            ]
                        , li []
                            [ a [ class "sidebar-link", href "datatable.html" ]
                                [ text "Data Table" ]
                            ]
                        ]
                    ]
                , li [ class "nav-item dropdown" ]
                    [ a [ class "dropdown-toggle", href "javascript:void(0);" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-purple-500 ti-map" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Maps" ]
                        , span [ class "arrow" ]
                            [ i [ class "ti-angle-right" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li []
                            [ a [ href "google-maps.html" ]
                                [ text "Google Map" ]
                            ]
                        , li []
                            [ a [ href "vector-maps.html" ]
                                [ text "Vector Map" ]
                            ]
                        ]
                    ]
                , li [ class "nav-item dropdown" ]
                    [ a [ class "dropdown-toggle", href "javascript:void(0);" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-red-500 ti-files" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Pages" ]
                        , span [ class "arrow" ]
                            [ i [ class "ti-angle-right" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li []
                            [ a [ class "sidebar-link", href "blank.html" ]
                                [ text "Blank" ]
                            ]
                        , li []
                            [ a [ class "sidebar-link", href "404.html" ]
                                [ text "404" ]
                            ]
                        , li []
                            [ a [ class "sidebar-link", href "500.html" ]
                                [ text "500" ]
                            ]
                        , li []
                            [ a [ class "sidebar-link", href "signin.html" ]
                                [ text "Sign In" ]
                            ]
                        , li []
                            [ a [ class "sidebar-link", href "signup.html" ]
                                [ text "Sign Up" ]
                            ]
                        ]
                    ]
                , li [ class "nav-item dropdown" ]
                    [ a [ class "dropdown-toggle", href "javascript:void(0);" ]
                        [ span [ class "icon-holder" ]
                            [ i [ class "c-teal-500 ti-view-list-alt" ]
                                []
                            ]
                        , span [ class "title" ]
                            [ text "Multiple Levels" ]
                        , span [ class "arrow" ]
                            [ i [ class "ti-angle-right" ]
                                []
                            ]
                        ]
                    , ul [ class "dropdown-menu" ]
                        [ li [ class "nav-item dropdown" ]
                            [ a [ href "javascript:void(0);" ]
                                [ span []
                                    [ text "Menu Item" ]
                                ]
                            ]
                        , li [ class "nav-item dropdown" ]
                            [ a [ href "javascript:void(0);" ]
                                [ span []
                                    [ text "Menu Item" ]
                                , span [ class "arrow" ]
                                    [ i [ class "ti-angle-right" ]
                                        []
                                    ]
                                ]
                            , ul [ class "dropdown-menu" ]
                                [ li []
                                    [ a [ href "javascript:void(0);" ]
                                        [ text "Menu Item" ]
                                    ]
                                , li []
                                    [ a [ href "javascript:void(0);" ]
                                        [ text "Menu Item" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
